### ISSUE TITLE
Update model DB

### ISSUE THREAD

**Issue by LeeinUITk17** [TDevUIT/PirateSocial#12]
![Image](https://github.com/user-attachments/assets/43d39c25-c0cf-479f-9b93-c7a38adaae3c)

dựa trên model , thiết kế bản db hoàn chỉnh hỗ trợ cho FACE#1 MessageBox.

output :
model db tương tự mongodb

**Comment by vanthaita** [comment]
### Tham Khảo SQL
[postgresql.txt](https://github.com/user-attachments/files/16869733/postgresql.txt)
[PostgreSql.pdf](https://github.com/user-attachments/files/16869713/PostgreSql.pdf)
![Postgresql](https://github.com/user-attachments/assets/e1153a0c-d347-4894-94c0-4d89445b1436)

**Comment by hirawaru** [comment]
Tham khảo model

![image](https://github.com/user-attachments/assets/b019db10-777c-4ef6-805a-0efd6d76ffd8)
